apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-logger
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: test-logger
    spec:
      containers:
        - name: test-logger
          image: gcr.io/cloud-solutions-images/test-logger